# Generated by Django 5.2 on 2025-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[(1, 'init'), (2, 'in_progress'), (3, 'finished')], default=1, max_length=20),
        ),
    ]
