# Generated by Django 5.2 on 2025-12-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_athleteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user',
            new_name='user_id',
        ),
    ]
